apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dpcdatabases.{{ .Values.controller.domain | required "controller.domain"}}
spec:
  group: {{ .Values.controller.domain }}
  names:
    kind: dpcdatabase
    plural: dpcdatabases
    singular: dpcdatabase
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                schema_name:
                  description: A name for the database schema to create.
                  type: string
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "Schema name cannot be changed."
                create_ssm:
                  description: Wether or not create an ssm parameter with the generated password
                  type: boolean
                  x-kubernetes-validations:
                    - rule: "self == oldSelf"
                      message: "create_ssm cannot be changed."
                drop_on_delete:
                  description: Specify if the database should be deleted with the object
                  type: boolean