{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-postgres-database-provisioner-controller.serviceAccountName" . }}
  namespace: database-provisioner-controller
  labels:
    {{- include "k8s-postgres-database-provisioner-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
